### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by resucutie** [GriefMoDz/smart-typers#1]
## Limit user typing
The user can add a limit to how many people are typing, instead of having the "Several People are typing" message

Ex: There are 5 persons typing and there is a limit setted by the user of 3 people
```
User1, User2, User3 and 2 more users are typing
```

Ex²: There are 5 persons typing and there is a limit setted by the user of 4 people
```
User1, User2, User3, User4 and 1 more user are typing
```

It can have a "inteligent hidding" mode, where the limit is how many users can fit in the screen
```
User1, User2 and 3 more people are typing (small res window)
```
```
User1, User2, User3, User4 and 1 more people are typing (maximized window)
```

## Custom message
Self explanatory, you can set a custom typing message
```
User1 is totally not typing...
User1 e User2 estão digitando...
User1, User2 and User3 are cute....
```

**Comment by GriefMoDz** [comment]
Partially landed in https://github.com/GriefMoDz/smart-typers/commit/1a62ecaf61f5e33a1d8cbbf6def4f1cc7aafff86 - still need to work on the "intelligent hiding" side of things, however most of the functionality such as limiting the amount of users shown and customizing the typing format is available to be tinkered with. Thanks for the feature request!

**Comment by resucutie** [comment]
Thanks. I noticed a bug on maximum typing users where when you set to 3 it doesn't applies the custom message. Everything else seems to be working okay. I was thinking about a option to remove the typing ball animation, and a tooltip containing all reaming people when the limit user typing hits (it can show the toast when hovering the typing user div)

**Comment by GriefMoDz** [comment]
> I noticed a bug on maximum typing users where when you set to 3 it doesn't applies the custom message.

I'm unable to reproduce this. Any chance that you could send me a screenshot of your settings?

> I was thinking about a option to remove the typing ball animation, and a tooltip containing all reaming people when the limit user typing hits (it can show the toast when hovering the typing user div)

These are some good suggestions, I'll see what I can do. Cheers!

**Comment by resucutie** [comment]
gonna close it so
